In [ ]:
import numpy as np

1.Arrays vs list comparison

In [ ]:
lst=[1,2,3]
print(lst)
print(type(lst))
print('-------')
arr=np.array([1,3,2])
print(arr)
print(type(arr))
print('-------')
print(arr == lst)
print(arr.tolist()== lst)
 #list only compares value not with other list and return true aur false but when one list is compared to array then it returns true or false with every element
print(sorted(arr)==sorted(lst))



[1, 2, 3]
<class 'list'>
-------
[1 3 2]
<class 'numpy.ndarray'>
-------
[ True False False]
False
True


2.Adding elements in an Array vs list

In [ ]:
lst=[1,2,3]
arr=np.array([1,2,3])
print(lst)
lst.append(4)
print(lst)
print('------')
print(arr)
arr=np.append(arr,4)
print(arr)

[1, 2, 3]
[1, 2, 3, 4]
------
[1 2 3]
[1 2 3 4]


3.Removing elements in an Array vs list

In [ ]:
lst=[1,2,3]
arr=np.array([1,2,3])
print(lst)
lst.pop()
#del lst[-1]
print(lst)
print('------')
print(arr)
arr=np.delete(arr,-2)
print(arr)

[1, 2, 3]
[1, 2]
------
[1 2 3]
[1 3]


4.Updating elements in an Array vs list(elements are updated to list with removal of element at mentioned index)

In [ ]:
lst=[1,2,3]
print(lst)
lst[-1]=4
lst[-2]=5
print(lst)

arr=np.array([1,2,3])
print(arr)
arr[-1]=9
arr[-2]=7
print(arr)

[1, 2, 3]
[1, 5, 4]
[1 2 3]
[1 7 9]


5.Array vs list comparison

In [ ]:
import time
my_list=list(range(1000000))
my_array=np.arange(1000000)
#search time for list
start_time=time.time()
for _ in range(100):
  if 5000000 in my_list:
    pass
end_time=time.time()
print('list:',end_time-start_time)
print('-------')

#search time for array
start_time=time.time()
for _ in range(100):
  if 5000000 in my_array:
    pass
end_time=time.time()
print('array:',end_time-start_time)


print(len(my_list))
print(len(my_array))


list: 1.6328885555267334
-------
array: 0.06655097007751465
1000000
1000000


In [ ]:
time.time()

1723959251.981858