In [ ]:
import numpy as np

1.Converting data structures to Numpy array

1.1)Converting a tuple to an array


In [ ]:
tpl=(1,2,3)
print(tpl)
print(type(tpl))
arr=np.array(tpl)
print(arr)
print(type(arr))


(1, 2, 3)
<class 'tuple'>
[1 2 3]
<class 'numpy.ndarray'>


1.2)Converting a list to an array

In [ ]:
lst=(1,2,3)
print(lst)
print(type(lst))
arr=np.array(lst)
print(arr)
print(type(arr))

(1, 2, 3)
<class 'tuple'>
[1 2 3]
<class 'numpy.ndarray'>


1.3)Converting a dictionary to an array

In [ ]:
dct={1:'apple',2:'banana',3:'cheery'}
print(dct)
print(type(dct))
arr=np.array(dct)
print(arr)
print(type(arr))
print('-----------')
arr_k=np.array(list(dct.keys()))
arr_v=np.array(list(dct.values()))
print(arr_k)
print(type(arr_k))
print(arr_v)
print(type(arr_v))


{1: 'apple', 2: 'banana', 3: 'cheery'}
<class 'dict'>
{1: 'apple', 2: 'banana', 3: 'cheery'}
<class 'numpy.ndarray'>
-----------
[1 2 3]
<class 'numpy.ndarray'>
['apple' 'banana' 'cheery']
<class 'numpy.ndarray'>


1.4)Converting a set to an array

In [ ]:
set_={1,2,3}
print(set_)
print(type(set_))
arr=np.array(list(set_))
print(arr)
print(type(arr))

{1, 2, 3}
<class 'set'>
[1 2 3]
<class 'numpy.ndarray'>


1.5)Converting string to an array

In [ ]:
arr=np.array('hello world')
print(arr)
print(type(arr))
arr=np.array(list('hello world'))
print(arr)
print(type(arr))

hello world
<class 'numpy.ndarray'>
['h' 'e' 'l' 'l' 'o' ' ' 'w' 'o' 'r' 'l' 'd']
<class 'numpy.ndarray'>


2.Converting the datatype of numpy array

2.1)Create an array of integers

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)
arr_=arr.astype('float')
print(arr_)
arr_=arr.astype('str')
print(arr_)
arr_=arr.astype('bool')
print(arr_)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
['1' '2' '3' '4' '5']
[ True  True  True  True  True]


2.2)Create an array of floats

In [ ]:
arr=np.array([1.,2.,3.,4.,5.])
print(arr)
arr_=arr.astype('int')
print(arr_)
arr_=arr.astype('str')
print(arr_)
arr_=arr.astype('bool')
print(arr_)


[1. 2. 3. 4. 5.]
[1 2 3 4 5]
['1.0' '2.0' '3.0' '4.0' '5.0']
[ True  True  True  True  True]


2.3)Create an array of string

In [ ]:
arr=np.array(['1','2','3','4','5'])
print(arr)
arr_=arr.astype('int')
print(arr_)
arr_=arr.astype('float')
print(arr_)
arr_=arr.astype('bool')
print(arr_)


['1' '2' '3' '4' '5']
[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[ True  True  True  True  True]


2.4)Create an array of Boolean

In [ ]:
arr=np.array([True,False,False,False,True])
print(arr)
arr_=arr.astype('int')
print(arr_)
arr_=arr.astype('float')
print(arr_)
arr_=arr.astype('str')
print(arr_)

[ True False False False  True]
[1 0 0 0 1]
[1. 0. 0. 0. 1.]
['True' 'False' 'False' 'False' 'True']


In [ ]:
arr=np.array([True,False,False,False,True])
print(arr)
arr_=arr.astype('int')
print(arr_)
arr_=arr_.astype('float')
print(arr_)

[ True False False False  True]
[1 0 0 0 1]
[1. 0. 0. 0. 1.]


In [ ]:
arr=np.array([True,False,False,False,True])
print(arr)
arr_=arr.astype('float')
print(arr_)
arr_=arr_.astype('str')
print(arr_)

[ True False False False  True]
[1. 0. 0. 0. 1.]
['1.0' '0.0' '0.0' '0.0' '1.0']
