In [ ]:
import numpy as np

1.Copy function with lists

In [ ]:
lst=[1,2,3,4,5]
print(lst)
lst1=lst

print(lst1)
print('-'*10)
lst[0]=5
print(lst)
print(lst1)
lst1[0]=4
print(lst)
print(lst1)


[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
----------
[5, 2, 3, 4, 5]
[5, 2, 3, 4, 5]
[4, 2, 3, 4, 5]
[4, 2, 3, 4, 5]


In [ ]:
lst=[1,2,3,4]
print(lst)
lst1=lst.copy()
print(lst1)
print('*'*20)
lst[0]=5
print(lst)
print(lst1)
lst1[0]=4
print(lst)
print(lst1)


[1, 2, 3, 4]
[1, 2, 3, 4]
********************
[5, 2, 3, 4]
[1, 2, 3, 4]
[5, 2, 3, 4]
[4, 2, 3, 4]


2)copy function with arrays

In [ ]:
arr=np.array([1,2,3,4])
arr_=arr.copy()
print(arr)
print(arr_)
print('-------------------------------')
arr[0]=5
print(arr)
print(arr_)
arr_[0]=6
print(arr)
print(arr_)

[1 2 3 4]
[1 2 3 4]
-------------------------------
[5 2 3 4]
[1 2 3 4]
[5 2 3 4]
[6 2 3 4]
