In [ ]:
import numpy as np

1.Zeroes

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((2,3,5), dtype=int)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

2.ones

In [ ]:
np.ones((5,3,2), dtype=int)

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

3.Eye

In [ ]:
np.eye(3)
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [ ]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

4.Random number generator

In [ ]:
print(np.random.rand())

0.058357771765749966


In [ ]:
for i in range(10):
  if(np.random.rand()>0.5):
    print("Head")
  else:
    print("Tail")

Tail
Head
Tail
Head
Tail
Tail
Tail
Tail
Head
Head


In [ ]:
print(np.random.rand(10))

[0.54043441 0.68800026 0.75154268 0.20256139 0.09792307 0.37316785
 0.12416261 0.69579271 0.68030713 0.29256659]


In [ ]:
print(np.random.rand(10,10))

[[0.2641809  0.86515775 0.27066786 0.74798698 0.65049544 0.37258899
  0.09118556 0.51006741 0.73251823 0.48988901]
 [0.11874641 0.13438662 0.99337588 0.65906556 0.74075867 0.05386234
  0.41187391 0.01448968 0.69881243 0.98085969]
 [0.30625222 0.03797484 0.12566241 0.75868668 0.1121893  0.2934444
  0.94927039 0.58893478 0.41380065 0.38581857]
 [0.53983104 0.36760308 0.3401473  0.42823212 0.82872967 0.22078985
  0.80119721 0.89705301 0.67763595 0.75863547]
 [0.60369621 0.97849292 0.24844186 0.11722323 0.03523013 0.88859251
  0.14439708 0.28059323 0.07482233 0.1800562 ]
 [0.89888405 0.03782437 0.77908013 0.00105556 0.92942535 0.16599322
  0.9447555  0.0041525  0.9172094  0.78153116]
 [0.85029347 0.36189059 0.99696952 0.25761037 0.30420603 0.24729461
  0.58515811 0.41484495 0.66382892 0.60552505]
 [0.24292275 0.34658586 0.47493798 0.22974757 0.14442748 0.107411
  0.04429087 0.90748375 0.84005383 0.70172899]
 [0.27599643 0.42301438 0.03612615 0.07703902 0.1958844  0.20716934
  0.10104083 0.

In [ ]:
np.random.randint(10,size=(3,3))

array([[0, 3, 1],
       [4, 9, 5],
       [1, 9, 3]])

In [ ]:
np.random.randint(low=1,high=7,size=(3,3))

array([[5, 6, 6],
       [2, 6, 5],
       [3, 4, 1]])

In [ ]:
np.random.randn()

0.3939357336791806

In [ ]:
np.random.uniform()

0.26423891534899546

In [ ]:
for i in range(10):
  print(np.random.randint(low=1,high=7))

3
3
5
2
2
6
3
2
5
5
