In [ ]:
import numpy as np

1.Indexing and slicing with lists

In [ ]:
lst=[23,34,56,78,45]
print(lst[-1])
print(lst[0])

45
23


In [ ]:
print(lst[0:4])
lst[:]
lst[1:-1]
lst[::2]
lst[1:-1:2]
lst[::-1]

[23, 34, 56, 78]


[45, 78, 56, 34, 23]

In [ ]:
lst[0]=100
lst

[100, 34, 56, 78, 45]

In [ ]:
del lst[0]
lst

[34, 56, 78, 45]

In [ ]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr[2]

3

In [ ]:
arr[1:-1:2]

array([2, 4])

In [ ]:
arr[0]=5
arr

array([5, 2, 3, 4, 5, 6])

In [ ]:
arr=np.delete(arr,0)
arr

array([2, 3, 4, 5, 6])

In [ ]:
arr=np.insert(arr,0,6)
arr
arr=np.insert(arr,0,9)
arr

array([9, 6, 6, 2, 3, 4, 5, 6])

In [ ]:
arr[::-1]
arr

array([9, 6, 6, 2, 3, 4, 5, 6])