In [ ]:
import numpy as np

In [ ]:
print(np.random.rand())
print(np.random.rand(3))
print(np.random.randint(10))
print(np.random.randint(10,size=(3,5)))


0.33584584422493025
[0.17040201 0.80640336 0.6501623 ]
3
[[0 6 2 1 0]
 [2 3 3 4 9]
 [3 5 7 6 3]]


with seed randomness can be managed different iterations will have same value

In [ ]:
np.random.seed(2)
print(np.random.rand())
print(np.random.rand(3))
print(np.random.randint(10))
print(np.random.randint(10,size=(3,5)))

0.43599490214200376
[0.02592623 0.54966248 0.43532239]
8
[[7 2 1 5 4]
 [4 5 7 3 6]
 [4 3 7 6 1]]


In [ ]:
np.random.seed(2)
print(np.random.rand())
print(np.random.rand(3))
print(np.random.randint(10))
print(np.random.randint(10,size=(3,5)))

0.43599490214200376
[0.02592623 0.54966248 0.43532239]
8
[[7 2 1 5 4]
 [4 5 7 3 6]
 [4 3 7 6 1]]
