In [ ]:
import numpy as np

1.Creating multi-dimensional arrays

1.1)Create a 2D array from a list of lists

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


1.2)Create a 3D array from a list of lists

In [ ]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]],
              [[1,2,3],[4,5,6],[7,8,9]],
              [[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


1.3)Create a 2D array from a list of tuples

In [ ]:
arr=np.array([(1,2,3),(4,5,6)])
print(arr)

[[1 2 3]
 [4 5 6]]


1.3)Create a 2D array from a list of arrays

In [ ]:
arr=np.array([np.array([1,2,3]), np.array([4,5,6])])
print(arr)

[[1 2 3]
 [4 5 6]]


1.3)Create a 2D array from a list of strings

In [ ]:
arr=np.array([['1','2','3'],['5','6','7']])
print(arr)

[['1' '2' '3']
 ['5' '6' '7']]


1.4)Create a 2D array from a list of dictionaries

In [ ]:
arr=np.array([{1:'a',2:'b',3:'c'},{4:'d',5:'e',6:'f'}])
print(arr)

[{1: 'a', 2: 'b', 3: 'c'} {4: 'd', 5: 'e', 6: 'f'}]


2.Finding details of an array

2.1)printing the shape of array



```
# `# This is formatted as code`
```



In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


2.2)printing the dimensions of array

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.ndim)

2


2.3)printing the data type of array

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.dtype)

int64


2.4)printing the size of array in bytes

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.size)

9


2.5)printing the total number of elements in an array(length of one element of array in bytes)

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.itemsize)

8


2.6)print the type of array

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>
